language: node_js
node_js:
  - "7"

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/docker-cache/

env:
  global:
    - COMPONENT=agile-example
    - DOCKER_CACHE_FILE=/home/travis/docker-cache/cache.tar.gz
  matrix:
    - DOCKER_IMAGE=agileiot/$COMPONENT-armv7l
    - DOCKER_IMAGE=agileiot/$COMPONENT-x86_64
      BASEIMAGE=resin\\/nuc-node:7.2.1

before_install:
  - git config --global user.name "Travis CI" && git config --global user.email "travis@travis-ci.org"
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - if [ "$BASEIMAGE" ] ; then sed -i "s/^FROM .*/FROM $BASEIMAGE/" Dockerfile ; fi
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";

script:
  - git tag
  - if [[ ${TRAVIS_PULL_REQUEST} != "false" ]]; then
      export DOCKER_TAG=$TRAVIS_PULL_REQUEST_BRANCH;
    fi
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" && -n ${TRAVIS_TAG} ]]; then
      export DOCKER_TAG=$TRAVIS_TAG;
    fi
after_success:
  - git pull --rebase && npm i;
  - echo $TRAVIS_PULL_REQUEST;
  - versionist
  - if [[ -n ${DOCKER_TAG} ]]; then
      docker push $DOCKER_IMAGE:$DOCKER_TAG;
    fi
